{% set name = 'sdv' %}
{% set version = '0.14.2.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - graphviz
    - python >=3.6,<3.10
    - faker >=3.0.0,<10
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - tqdm >=4.15,<5
    - copulas >=0.6.0,<0.7
    - ctgan >=0.5.0,<0.6
    - deepecho >=0.3.0.post1,<0.4
    - rdt >=0.6.1,<0.7
    - sdmetrics >=0.4.1,<0.5
  run:
    - graphviz
    - python >=3.6,<3.10
    - faker >=3.0.0,<10
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - tqdm >=4.15,<5
    - copulas >=0.6.0,<0.7
    - ctgan >=0.5.0,<0.6
    - deepecho >=0.3.0.post1,<0.4
    - rdt >=0.6.1,<0.7
    - sdmetrics >=0.4.1,<0.5

about:
  home: "https://sdv.dev"
  license: MIT
  license_family: MIT
  license_file: "LICENSE"
  summary: "Synthetic Data Generation for tabular, relational and time series data."
  doc_url: "https://sdv.dev/SDV"
  dev_url: "https://github.com/sdv-dev/SDV"

extra:
  recipe-maintainers:
    - sdv-dev
